import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import FooterWrapper from "@/components/wrapper/FooterWrapper";

const font = Red_Hat_Display({ subsets: ["latin"] });

export const metadata = {
  title: "Makinft || Home",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body style={{ background: "#15161b" }} className={font.className}>
        {children}
        <FooterWrapper />
      </body>
    </html>
  );
};
export default RootLayout;
